# Generated by Django 5.0.4 on 2024-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("data_field", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
